### ISSUE TITLE
Fix zoom prototype

### ISSUE THREAD

**Issue by JelloRanger** [JelloRanger/MapGenerator#9]
There's a zoom function "setZoom" in the code. Users should be able to zoom in/out on the map relative to their mouse cursor, and drag the map with their mouse.

**Comment by odinsbane** [comment]
I made a mock up of a zoom. I am not sure what is missing from this. It is a self-contained program, so you can build it and try it out.

http://pastie.org/10937379

**Comment by JelloRanger** [comment]
Thanks for the help. I managed to get it working in the latest commit! :)
